import type { Metadata } from "next";
import { Teko } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const TekoFont = Teko({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${TekoFont} antialiased`}>
                {children}
                <Toaster position='top-right' />
            </body>
        </html>
    );
}
